---
title: "Equipo de investigación"

output: html_document
---





#### <font face="Arial Black">  Centro de Economía y Política Regional: </font>

- <a href="aroca.html"> Patricio Aroca </a>

    + Rol: Investigador Responsable
    + Institución: Universidad Adolfo Ibáñez
    + Contacto: patricio.aroca@uai.cl


- <a href="eberhard.html"> Juan Pedro Eberhard </a>

    + Rol: Investigador Asociado
    + Institución: Universidad Adolfo Ibáñez
    + Contacto: juan.eberhard@uai.cl

- <a href="garrido.html"> Nicolás Garrido </a>

    + Rol: Investigador Asociado
    + Institución: Universidad Diego Portales
    + Contacto: nicolas.garrido@udp.cl
  

- <a href="valdebenito.html"> Rocío Valdebenito </a>

    + Rol: Ayudante de Investigación
    + Institución: Centro de Economía y Política Regional
    + Contacto: rocio.valdebenito@uai.cl

- <a href="morales.html"> Felipe Morales </a>

    + Rol: Ayudante de Investigación
    + Institución: Centro de Economía y Política Regional
    + Contacto: f.morales@uai.cl
    
#### <font face="Arial Black">  Institute of Economics Structure Research: </font>

- <a href="anke.html"> Anke Mönning </a>

    + Rol: Investigadora Responsable en el Extranjero
    + Institución: GWS mbH (Institute of Economics Structures Research)
    + Contacto: moenning@gws-os.com
  
- <a href="marc.html">Marc Ingo Wolter </a>

    + Rol: Investigador Asociado en el Extranjero
    + Institución: GWS mbH (Institute of Economics Structures Research)
    + Contacto: wolter@gws-os.com
  
- Anett Groẞmann

    + Rol: Investigador Asociado en el Extranjero
    + Institución: GWS mbH (Institute of Economics Structures Research)
    + Contacto: grossman@gws-os.com

- <a href="loreto.html">Loreto Bieritz </a>

    + Rol: Investigador Asociado en el Extranjero
    + Institución: GWS mbH (Institute of Economics Structures Research)
    + Contacto:  bieritz@gws-os.com

- <a href="hohmann.html">Frank Hohmann </a>

    + Rol: Investigador Asociado en el Extranjero
    + Institución: GWS mbH (Institute of Economics Structures Research)
    + Contacto:  hohmann@gws-os.com


- <a href="index.html"> Volver al Índice </a>