---
output: html_document
---

<style>
body {background-color: powderblue;}
h1   {color: grey;}
p    {color: black;}
.topnav {
  overflow: hidden;
  background-color: #333;
}

</style>

           
### <font face="Arial Black">  Resultados Preliminares </font>

<html>
<body style=”text-align: justify;”>

<p style=”text-align: justify;”> A través del desarrollo de un modelo que permitirá analizar los alcances de shocks de precios internos y externos sobre el sector minero, tanto a nivel nacional como espacial, este proyecto busca generar información relevante para la discusión y elaboración de políticas públicas enfocadas especialmente en las evaluaciones de impacto de políticas aplicadas al sector minero. </p>

<p style=”text-align: justify;”> Uno de los principales aportes que espera entregar estre proyecto es el desarrollo de un nuevo instrumental, conocido como los modelo REIM (Regional Econometrics Input Output Models), que permite desarrollar evaluaciones de impacto de shocks en variables económicas tanto a nivel nacional como nivel regional. Esto permitirá mejorar los alcances de información de hacedores de políticas públicas limitados para el análisis espacial con los REIM. </p>   

<p style=”text-align: justify;”>  </p>

Mira los resultados del proyecto COFORCE aquí:
 
- General Model:

 <a href="http://www.coforce.cl/resultados_preliminares/paper_anke.html">  Methodology and design of a macro-econometric input-output model for the Chilean economy</a>

- Tax Scenarios:

-Labor Data:
 <a href="http://www.coforce.cl/resultados_preliminares/paper_lopez.html">  Data accuracy and economic modelling</a>



- Energy Scenario:
 <a href="http://www.coforce.cl/resultados_preliminares/paper_garrido.html">  economic asssessment of the changes in the energy sources on the chilean mining sector</a>

</body>
</html>